# This is a basic workflow to help you get started with Actions
name: Publish

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
    paths:
    - '**publish.yml'
    - '**.scrbl'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Cache installed packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.racket
          key: ${{ runner.os }}-primes
      - uses: Bogdanp/setup-racket@v1.4
        with:
          architecture: 'x64'
          distribution: 'minimal'
          variant: 'CS'
          version: '8.0'
      - name: Build
        run: |
          raco pkg install --auto
          make build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: doc_build
          publish_branch: master
